### ISSUE TITLE
Chunck mispelled

### ISSUE THREAD

**Issue by hadley** [paulponcet/lplyr#2]
Should be chunk?

I think this could also go in multidplyr if you were interested.

**Comment by paulponcet** [comment]
Thanks, just made the correction. Indeed I can make a pull request on 'multidplyr'. 

Do you think 'multidplyr' could be on CRAN soon? What should be done for this?

**Comment by hadley** [comment]
I'd like to get it on CRAN by the end of the year - there's a major bug in `partition()` that needs to be fixed, but probably not too much more.  The main thing I'm waiting for is some better parallel foundations so that I don't have to export a whole bunch of stuff that's not directly related to multidplyr in order to make it somewhat usable
